name: disease-detection
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pip
  - pyyaml
  - pillow
  - numpy
  - tqdm
  - pip:
      - python-dotenv
      - hydra-core>=1.3
      - omegaconf>=2.3
      - torchmetrics>=1.4
      - pycocotools>=2.0
      - pytorch-lightning>=2.3
      - pytest>=8
      - pytest-mock
      - ruff
      - black
      - -e .
